name: Packages

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-packages-debian:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["amd64"]

    name: Package (Debian, ${{ matrix.pkgarch }})

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install webkit2gtk-4.0
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.0-dev gtk+-3.0 webkit2gtk-4.0
          version: 1.0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build package
        env:
          PKGARCH: ${{ matrix.pkgarch }}
        run: |
          PKGARCH=${{ matrix.pkgarch }} sh ./contrib/deb/generate.sh
          PKGARCH=${{ matrix.pkgarch }} sh ./contrib/deb/generate-gui.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debian package (${{ matrix.pkgarch }})
          path: "*.deb"
          if-no-files-found: error

  build-packages-macos:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["amd64"]

    name: Package (macOS, ${{ matrix.pkgarch }})

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build package
        env:
          PKGARCH: ${{ matrix.pkgarch }}
        run: |
          PKGARCH=${{ matrix.pkgarch }} sh contrib/macos/create-pkg-gui.sh
          PKGARCH=${{ matrix.pkgarch }} sh contrib/macos/create-pkg.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macOS package (${{ matrix.pkgarch }})
          path: "*.pkg"
          if-no-files-found: error

  build-packages-windows:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["x64", "x86"]

    name: Package (Windows, ${{ matrix.pkgarch }})

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build package
        run: |
          sh ./contrib/msi/build-msi-gui.sh ${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows package (${{ matrix.pkgarch }})
          path: "*.msi"
          if-no-files-found: error
